#!/usr/bin/env python3
"""Fail when a committed banner block has drifted from the template it came from.

Issue #85, fallout from #83.

THE PROBLEM THIS SOLVES. The demo docs quote rendered guest artifacts —
/etc/issue.net, /etc/motd, facts.json — in fenced code blocks. Every copy is
hand-pasted: `render-demo-assets.py` prints to stdout and writes nothing into
markdown. Edit motd.j2 and the docs go stale with CI green.

That matters more than usual here. These blocks are what the demo falls back to
when there is no cluster, so a stale banner has a presenter describing a machine
that does not exist, in front of a customer.

HOW A BLOCK IS FOUND. By an explicit marker comment on the line above the fence:

    <!-- rendered: motd.j2 -->
    ```text
    ...
    ```

Not by matching the surrounding prose, which breaks the moment someone rewords a
sentence. The marker also makes the coupling visible to whoever edits the doc
next, which is the actual failure this guards against.

WHY IT IMPORTS THE RENDERER RATHER THAN PARSING ITS STDOUT. render-demo-assets.py
wraps each artifact in a decorative `====` banner for humans. Scraping that would
couple this check to the *presentation* of a script whose job is to print things
nicely, so a cosmetic change to the banner would fail the docs gate. Calling
render() and facts_json() compares against the same values the script does.

WHAT IS DELIBERATELY NOT CHECKED. demo-page.png. It is a Chrome screenshot, and a
byte diff would fail on a Chrome or font-rendering change rather than on real
drift. The PNG is regenerated deliberately, not verified.

Needs only jinja2 — no Chrome — so it runs in seconds in CI.
"""

from __future__ import annotations

import difflib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "utilities"))

try:
    import importlib

    _renderer = importlib.import_module("render-demo-assets".replace("-", "_"))
except ModuleNotFoundError:
    # The module's filename has hyphens, so it cannot be imported by name.
    # Load it by path instead. Kept explicit rather than renaming the script,
    # which other docs and the run-sheet reference by name.
    import importlib.util

    _spec = importlib.util.spec_from_file_location(
        "render_demo_assets", REPO / "utilities" / "render-demo-assets.py"
    )
    if _spec is None or _spec.loader is None:  # pragma: no cover
        print("ERROR: cannot load utilities/render-demo-assets.py", file=sys.stderr)
        raise SystemExit(2)
    _renderer = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_renderer)


# Marker name -> a callable returning the authoritative text.
#
# The key is what appears in `<!-- rendered: <key> -->`. Template artifacts use
# the template's own filename so the marker names its source of truth directly;
# facts.json is generated by a function and is named for the file it becomes.
SOURCES = {
    "issue.j2": lambda: _renderer.render("issue.j2"),
    "motd.j2": lambda: _renderer.render("motd.j2"),
    "facts.json": _renderer.facts_json,
}

DOCS_ROOT = REPO / "docs"

MARKER = re.compile(
    r"<!--\s*rendered:\s*(?P<name>[\w.\-]+)\s*-->\s*\n"
    r"```[a-zA-Z0-9]*\n"
    r"(?P<body>.*?)"
    r"```",
    re.DOTALL,
)


def main() -> int:
    rendered = {}
    for name, fn in SOURCES.items():
        try:
            rendered[name] = fn().rstrip("\n")
        except Exception as exc:  # noqa: BLE001 - report, do not crash
            print(f"ERROR: could not render {name}: {exc}", file=sys.stderr)
            return 2

    failures = 0
    checked = 0
    seen: set[str] = set()

    for doc in sorted(DOCS_ROOT.rglob("*.md")):
        text = doc.read_text(encoding="utf-8")
        for m in MARKER.finditer(text):
            name = m.group("name")
            rel = doc.relative_to(REPO)

            if name not in rendered:
                print(
                    f"::error file={rel}::unknown rendered marker '{name}' — "
                    f"expected one of {', '.join(sorted(rendered))}"
                )
                failures += 1
                continue

            seen.add(name)
            checked += 1
            want = rendered[name]
            got = m.group("body").rstrip("\n")

            if got == want:
                continue

            failures += 1
            line = text[: m.start()].count("\n") + 1
            print(f"::error file={rel},line={line}::block '{name}' has drifted")
            print(f"\n--- {rel} (committed, line {line})")
            print(f"+++ {name} (rendered now)")
            diff = difflib.unified_diff(
                got.splitlines(),
                want.splitlines(),
                lineterm="",
                n=2,
            )
            for d in list(diff)[2:]:
                print(d)
            print()

    # A marker that no document carries means the coupling was silently dropped
    # — the exact drift this exists to catch, one level up. Fail rather than
    # report a cheerful zero.
    for name in sorted(set(rendered) - seen):
        print(
            f"::error::no document carries '<!-- rendered: {name} -->' — "
            f"the artifact is no longer verified anywhere"
        )
        failures += 1

    if failures:
        print(
            f"\n{failures} problem(s). Re-run "
            f"`python3 utilities/render-demo-assets.py --no-png` and paste the "
            f"current output into the block(s) above.",
            file=sys.stderr,
        )
        return 1

    print(f"Docs artifacts current: {checked} block(s) match their templates.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
