#!/usr/bin/env python3
"""Generate inventory/env-urls.yml from the committed connection.yml files.

Issue #426, #429.

Every Route hostname in this platform follows a fixed prefix plus the cluster's
*.apps domain.  The apps domain is already committed in each environment's
connection.yml as ``openshift_apps_domain``, so the URLs are deterministic —
but discovering them via MCP burns tokens every session.  This script reads
that one key from each environment and writes a gitignored YAML file that
Claude (or a human) can read directly.

With ``--with-creds``, the output also includes usernames (from connection.yml)
and passwords (decrypted from the vault).  The file is gitignored, so
credentials never reach the remote.

Regenerate after repointing an environment (new RHDP cluster, edge rebuild).

Usage:
    python3 utilities/generate-env-urls.py                # URLs only
    python3 utilities/generate-env-urls.py --with-creds   # URLs + credentials
    python3 utilities/generate-env-urls.py --check         # exits non-zero if stale
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import subprocess
import sys
from typing import Any, Dict, List, Optional, Tuple

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
GROUP_VARS = REPO_ROOT / "inventory" / "group_vars"
OUTPUT = REPO_ROOT / "inventory" / "env-urls.yml"

ROUTE_PREFIXES: List[Tuple[str, str]] = [
    ("aap", "aap-aap"),
    ("ocp_console", "console-openshift-console"),
    ("ocp_oauth", "oauth-openshift"),
    ("ao", "ao-automation-orchestrator"),
    ("portal", "rhaap-portal-aap-portal"),
]

APPS_DOMAIN_RE = re.compile(
    r'^openshift_apps_domain:\s*["\']?([^"\'#\s]+)["\']?\s*$'
)

USERNAME_KEYS = ["aap_username", "linux_admin_username", "windows_admin_username"]
USERNAME_RES = {
    key: re.compile(rf'^{key}:\s*["\']?([^"\'#\s]+)["\']?\s*$')
    for key in USERNAME_KEYS
}

CREDENTIAL_KEYS = [
    "aap_password",
    "openshift_api_token",
    "linux_admin_password",
    "windows_admin_password",
]


def read_apps_domain(connection: pathlib.Path) -> str | None:
    for line in connection.read_text().splitlines():
        m = APPS_DOMAIN_RE.match(line)
        if m:
            return m.group(1)
    return None


def read_usernames(connection: pathlib.Path) -> Dict[str, str]:
    usernames: Dict[str, str] = {}
    for line in connection.read_text().splitlines():
        for key, pattern in USERNAME_RES.items():
            m = pattern.match(line)
            if m:
                usernames[key] = m.group(1)
    return usernames


def read_vault_secrets() -> Optional[Dict[str, Dict[str, str]]]:
    """Decrypt secrets.yml and return the env_secrets mapping."""
    vault_pass = os.environ.get(
        "SALES_DEMOS_VAULT_PASS",
        str(pathlib.Path.home() / "secrets" / ".vault_pass_sales_demos"),
    )
    secrets_path = REPO_ROOT / "playbooks" / "group_vars" / "all" / "secrets.yml"

    if not secrets_path.exists():
        print(f"WARNING: {secrets_path} not found, skipping credentials", file=sys.stderr)
        return None
    if not pathlib.Path(vault_pass).exists():
        print(f"WARNING: vault password file {vault_pass} not found", file=sys.stderr)
        return None

    try:
        import yaml  # noqa: PLC0415
    except ImportError:
        print("WARNING: pyyaml not installed, skipping credentials", file=sys.stderr)
        return None

    try:
        result = subprocess.run(
            [
                "ansible-vault", "view", str(secrets_path),
                "--vault-password-file", vault_pass,
            ],
            capture_output=True, text=True, check=True,
        )
    except FileNotFoundError:
        print("WARNING: ansible-vault not found, skipping credentials", file=sys.stderr)
        return None
    except subprocess.CalledProcessError as exc:
        print(f"WARNING: ansible-vault failed: {exc.stderr.strip()}", file=sys.stderr)
        return None

    try:
        data: Dict[str, Any] = yaml.safe_load(result.stdout) or {}
    except yaml.YAMLError as exc:
        print(f"WARNING: could not parse vault output: {exc}", file=sys.stderr)
        return None

    return data.get("env_secrets")


def discover_environments() -> Dict[str, str]:
    envs: Dict[str, str] = {}
    for env_dir in sorted(GROUP_VARS.iterdir()):
        conn = env_dir / "connection.yml"
        if not conn.is_file():
            continue
        domain = read_apps_domain(conn)
        if domain:
            envs[env_dir.name] = domain
    return envs


def build_yaml(
    envs: Dict[str, str],
    *,
    with_creds: bool = False,
    usernames: Optional[Dict[str, Dict[str, str]]] = None,
    secrets: Optional[Dict[str, Dict[str, str]]] = None,
) -> str:
    regen_cmd = "python3 utilities/generate-env-urls.py"
    if with_creds:
        regen_cmd += " --with-creds"
    lines = [
        "# Auto-generated by utilities/generate-env-urls.py. Do not commit.",
        "# Regenerate after repointing an environment:",
        f"#   {regen_cmd}",
        "---",
    ]
    for env_name, domain in envs.items():
        lines.append(f"{env_name}:")
        for key, prefix in ROUTE_PREFIXES:
            lines.append(f'  {key}: "https://{prefix}.{domain}/"')

        if with_creds:
            env_usernames = (usernames or {}).get(env_name, {})
            env_secrets = (secrets or {}).get(env_name, {})
            if env_usernames or env_secrets:
                lines.append("  credentials:")
                if "aap_username" in env_usernames:
                    lines.append(f'    aap_username: "{env_usernames["aap_username"]}"')
                if "aap_password" in env_secrets:
                    lines.append(f'    aap_password: "{env_secrets["aap_password"]}"')
                if "openshift_api_token" in env_secrets:
                    lines.append(f'    openshift_api_token: "{env_secrets["openshift_api_token"]}"')
                if "linux_admin_username" in env_usernames:
                    lines.append(f'    linux_admin_username: "{env_usernames["linux_admin_username"]}"')
                if "linux_admin_password" in env_secrets:
                    lines.append(f'    linux_admin_password: "{env_secrets["linux_admin_password"]}"')
                if "windows_admin_username" in env_usernames:
                    lines.append(f'    windows_admin_username: "{env_usernames["windows_admin_username"]}"')
                if "windows_admin_password" in env_secrets:
                    lines.append(f'    windows_admin_password: "{env_secrets["windows_admin_password"]}"')

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the file is missing or stale (do not write).",
    )
    parser.add_argument(
        "--with-creds",
        action="store_true",
        help="Include usernames and vault-decrypted passwords in the output.",
    )
    args = parser.parse_args()

    envs = discover_environments()
    if not envs:
        print("ERROR: no environments found under", GROUP_VARS, file=sys.stderr)
        raise SystemExit(1)

    # aap is the shared group, not an environment
    envs.pop("aap", None)

    usernames: Optional[Dict[str, Dict[str, str]]] = None
    secrets: Optional[Dict[str, Dict[str, str]]] = None

    if args.with_creds:
        usernames = {}
        for env_name in envs:
            conn = GROUP_VARS / env_name / "connection.yml"
            if conn.is_file():
                usernames[env_name] = read_usernames(conn)
        secrets = read_vault_secrets()

    content = build_yaml(envs, with_creds=args.with_creds, usernames=usernames, secrets=secrets)

    if args.check:
        # --check compares URL-only output regardless of --with-creds, because
        # CI has no vault access.
        check_content = build_yaml(envs)
        if not OUTPUT.exists():
            print(f"MISSING: {OUTPUT.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("Run: python3 utilities/generate-env-urls.py", file=sys.stderr)
            raise SystemExit(1)
        existing = OUTPUT.read_text()
        # The file may have been generated with or without creds. For --check
        # we only verify the URL lines are present and current.
        existing_urls = build_yaml(envs)
        if not _urls_match(existing, existing_urls):
            print(f"STALE: {OUTPUT.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("Run: python3 utilities/generate-env-urls.py", file=sys.stderr)
            raise SystemExit(1)
        print(f"OK: {OUTPUT.relative_to(REPO_ROOT)} is current")
        return

    OUTPUT.write_text(content)
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    for env_name in envs:
        detail = f"{len(ROUTE_PREFIXES)} URLs"
        if args.with_creds:
            detail += " + credentials"
        print(f"  {env_name}: {detail}")


def _urls_match(existing: str, expected_urls: str) -> bool:
    """Check that every URL line in expected_urls appears in existing."""
    expected_url_lines = {
        line.strip()
        for line in expected_urls.splitlines()
        if "https://" in line
    }
    existing_lines = {line.strip() for line in existing.splitlines()}
    return expected_url_lines.issubset(existing_lines)


if __name__ == "__main__":
    main()
