#!/usr/bin/env python3
"""Generate inventory/env-urls.yml from the committed connection.yml files.

Issue #426.

Every Route hostname in this platform follows a fixed prefix plus the cluster's
*.apps domain.  The apps domain is already committed in each environment's
connection.yml as ``openshift_apps_domain``, so the URLs are deterministic —
but discovering them via MCP burns tokens every session.  This script reads
that one key from each environment and writes a gitignored YAML file that
Claude (or a human) can read directly.

Regenerate after repointing an environment (new RHDP cluster, edge rebuild).

Usage:
    python3 utilities/generate-env-urls.py          # writes inventory/env-urls.yml
    python3 utilities/generate-env-urls.py --check   # exits non-zero if stale
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from typing import Dict, List, Tuple

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
GROUP_VARS = REPO_ROOT / "inventory" / "group_vars"
OUTPUT = REPO_ROOT / "inventory" / "env-urls.yml"

ROUTE_PREFIXES: List[Tuple[str, str]] = [
    ("aap", "aap-aap"),
    ("ocp_console", "console-openshift-console"),
    ("ocp_oauth", "oauth-openshift"),
    ("ao", "ao-automation-orchestrator"),
    ("portal", "rhaap-portal-aap-portal"),
]

APPS_DOMAIN_RE = re.compile(
    r'^openshift_apps_domain:\s*["\']?([^"\'#\s]+)["\']?\s*$'
)


def read_apps_domain(connection: pathlib.Path) -> str | None:
    for line in connection.read_text().splitlines():
        m = APPS_DOMAIN_RE.match(line)
        if m:
            return m.group(1)
    return None


def discover_environments() -> Dict[str, str]:
    envs: Dict[str, str] = {}
    for env_dir in sorted(GROUP_VARS.iterdir()):
        conn = env_dir / "connection.yml"
        if not conn.is_file():
            continue
        domain = read_apps_domain(conn)
        if domain:
            envs[env_dir.name] = domain
    return envs


def build_yaml(envs: Dict[str, str]) -> str:
    lines = [
        "# Auto-generated by utilities/generate-env-urls.py. Do not commit.",
        "# Regenerate after repointing an environment:",
        "#   python3 utilities/generate-env-urls.py",
        "---",
    ]
    for env_name, domain in envs.items():
        lines.append(f"{env_name}:")
        for key, prefix in ROUTE_PREFIXES:
            lines.append(f'  {key}: "https://{prefix}.{domain}/"')
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the file is missing or stale (do not write).",
    )
    args = parser.parse_args()

    envs = discover_environments()
    if not envs:
        print("ERROR: no environments found under", GROUP_VARS, file=sys.stderr)
        raise SystemExit(1)

    # aap is the shared group, not an environment
    envs.pop("aap", None)

    content = build_yaml(envs)

    if args.check:
        if not OUTPUT.exists():
            print(f"MISSING: {OUTPUT.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("Run: python3 utilities/generate-env-urls.py", file=sys.stderr)
            raise SystemExit(1)
        if OUTPUT.read_text() != content:
            print(f"STALE: {OUTPUT.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("Run: python3 utilities/generate-env-urls.py", file=sys.stderr)
            raise SystemExit(1)
        print(f"OK: {OUTPUT.relative_to(REPO_ROOT)} is current")
        return

    OUTPUT.write_text(content)
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    for env_name in envs:
        print(f"  {env_name}: {len(ROUTE_PREFIXES)} URLs")


if __name__ == "__main__":
    main()
