#!/usr/bin/env bash
# ===========================================================================
# make-kubeconfig.sh — synthesise a kubeconfig for one environment, for the
# OpenShift MCP server to authenticate with. Issue #102.
#
#   bash utilities/make-kubeconfig.sh sandbox
#   bash utilities/make-kubeconfig.sh demo
#
# WHY THIS EXISTS. kubernetes-mcp-server authenticates by kubeconfig, and this
# repo keeps its cluster credentials in a vault, not in one. Rather than ask
# every user to `oc login` and hope their current context is the environment
# they meant, this derives a kubeconfig from the same two sources everything
# else here uses:
#
#   openshift_api_url    committed plaintext, group_vars/<env>/connection.yml
#   openshift_api_token  vault-encrypted,     playbooks/group_vars/all/secrets.yml
#
# ONE FILE PER ENVIRONMENT, NAMED AFTER IT. That is the whole point. #16 is the
# precedent: when `sandbox` and `demo` were not kept distinct, `--limit demo`
# silently resolved to sandbox's hostname and sandbox's token with no warning.
# A single shared kubeconfig whose contents change would reintroduce exactly
# that failure, so .mcp.json names one server per environment and each is
# pinned to its own file.
#
# THE OUTPUT IS A REAL CREDENTIAL. It lands in .kube/, which .gitignore already
# covers, and is written 0600. It is derived, never authoritative — delete it
# and re-run this any time. Rotating the token means editing the vault and
# re-running; this file is a copy and will go stale silently otherwise.
# ===========================================================================
set -euo pipefail

ENV_NAME="${1:-}"
if [[ -z "$ENV_NAME" ]]; then
  echo "usage: bash utilities/make-kubeconfig.sh <sandbox|demo>" >&2
  exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [[ ! -d "inventory/group_vars/$ENV_NAME" ]]; then
  echo "❌ unknown environment '$ENV_NAME' — expected one of:" >&2
  ls -1 inventory/group_vars | grep -v '^aap$' | sed 's/^/     /' >&2
  exit 2
fi

# The default is the convention; SALES_DEMOS_VAULT_PASS repoints it for someone
# who keeps vault passwords elsewhere. The SAME env var is read by
# inventory/group_vars/aap/main.yml, so one export moves both this script and
# the AAP Vault credential together rather than leaving them disagreeing (#131).
VAULT_PASS="${SALES_DEMOS_VAULT_PASS:-$HOME/secrets/.vault_pass_sales_demos}"
VAULT_ID="sales.demos@$VAULT_PASS"
if [[ ! -s "$VAULT_PASS" ]]; then
  echo "❌ $VAULT_PASS missing — without it the secrets file cannot be decrypted." >&2
  echo "   Build it with /sales-demos-first-time, step 2, or set" >&2
  echo "   SALES_DEMOS_VAULT_PASS if yours lives somewhere else." >&2
  exit 1
fi

# The API URL is plaintext and lives next to the INVENTORY, so ad-hoc ansible
# resolves it — and --limit proves the environment selection at the same time.
API_URL="$(ansible -i inventory --limit "$ENV_NAME" aap -m debug --vault-id "$VAULT_ID" \
  -a 'msg={{ openshift_api_url }}' 2>/dev/null | sed -n 's/.*"msg": "\(.*\)"/\1/p')"

# The token is vaulted and lives next to the PLAYBOOKS. An ad-hoc command has no
# playbook, so that group_vars directory is never loaded and the lookup fails
# with 'env_secrets' is undefined. Read it through the vault instead (#86).
API_TOKEN="$(ansible-vault view playbooks/group_vars/all/secrets.yml --vault-id "$VAULT_ID" 2>/dev/null \
  | ENV_NAME="$ENV_NAME" python3 -c \
      'import sys,yaml,os; print(yaml.safe_load(sys.stdin)["env_secrets"][os.environ["ENV_NAME"]]["openshift_api_token"])')"

# CHECK THE SHAPE, NOT JUST THAT SOMETHING CAME BACK. `-m debug` prints its own
# errors into the same "msg" field this scrapes, so a failed lookup yields error
# TEXT — non-empty, and a bare `test -n` would call that success (#86).
case "$API_URL" in
  https://*) ;;
  *) echo "❌ could not resolve $ENV_NAME API URL — got: ${API_URL:0:60}" >&2; exit 1 ;;
esac

# Two token forms are valid and both are in use here: the sha256~ OAuth token,
# and a ServiceAccount JWT, which does not expire. See #105 — a check that
# accepted only the first rejected a perfectly good credential.
case "$API_TOKEN" in
  sha256~*)  TOKEN_KIND="OAuth token" ;;
  eyJ*.*.*)  TOKEN_KIND="ServiceAccount token" ;;
  *) echo "❌ could not resolve $ENV_NAME token — check the vault and env_secrets.$ENV_NAME" >&2; exit 1 ;;
esac

CLUSTER_HOST="${API_URL#https://}"
CLUSTER_NAME="${ENV_NAME}"
OUT_DIR="$REPO_ROOT/.kube"
OUT="$OUT_DIR/${ENV_NAME}.kubeconfig"

mkdir -p "$OUT_DIR"
# Create empty and lock it down BEFORE the token is written, so the secret is
# never briefly world-readable.
umask 077
: > "$OUT"
chmod 600 "$OUT"

cat > "$OUT" <<YAML
# Generated by utilities/make-kubeconfig.sh — DO NOT EDIT, DO NOT COMMIT.
# Derived from inventory/group_vars/${ENV_NAME}/connection.yml and the vault.
# Regenerate after rotating openshift_api_token; this copy goes stale silently.
apiVersion: v1
kind: Config
current-context: ${CLUSTER_NAME}
clusters:
  - name: ${CLUSTER_NAME}
    cluster:
      server: ${API_URL}
      # RHDP clusters serve a self-signed API certificate. The *.apps ingress
      # certificate is publicly trusted, but the :6443 endpoint is not.
      insecure-skip-tls-verify: true
users:
  - name: ${CLUSTER_NAME}-user
    user:
      token: ${API_TOKEN}
contexts:
  - name: ${CLUSTER_NAME}
    context:
      cluster: ${CLUSTER_NAME}
      user: ${CLUSTER_NAME}-user
YAML

echo "✅ wrote $OUT (0600)"
echo "   environment : $ENV_NAME"
echo "   cluster     : $CLUSTER_HOST"
echo "   credential  : $TOKEN_KIND"
